source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'MandrakeKitDemo' do
    pod 'MandrakeKit', :podspec => '../MandrakeKit.podspec'
    pod 'LayoutKit', :git => 'https://github.com/rocry/LayoutKit', :branch => 'master'
end
