source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bearyinnovative/MandrakeKit'
platform :ios, '9.0'
use_frameworks!

target 'MandrakeKitDemo' do
    pod 'MandrakeKit', '0.1.0.beta.1'
end

target 'MandrakeKitDemo-OC' do
    pod 'MandrakeKit', '0.1.0.beta.1'
end
